package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String depNombre;
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, String depNombre) {
        this.idDepartamento = idDepartamento;
        this.depNombre = depNombre;
    }
    public Departamento(int idDepartamento, String depNombre, Set<Ciudad> ciudads) {
       this.idDepartamento = idDepartamento;
       this.depNombre = depNombre;
       this.ciudads = ciudads;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getDepNombre() {
        return this.depNombre;
    }
    
    public void setDepNombre(String depNombre) {
        this.depNombre = depNombre;
    }
    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }




}


