package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoLinea generated by hbm2java
 */
public class EstadoLinea  implements java.io.Serializable {


     private Integer idEstadoLinea;
     private String estLinNombre;
     private Set<Linea> lineas = new HashSet<Linea>(0);

    public EstadoLinea() {
    }

	
    public EstadoLinea(String estLinNombre) {
        this.estLinNombre = estLinNombre;
    }
    public EstadoLinea(String estLinNombre, Set<Linea> lineas) {
       this.estLinNombre = estLinNombre;
       this.lineas = lineas;
    }
   
    public Integer getIdEstadoLinea() {
        return this.idEstadoLinea;
    }
    
    public void setIdEstadoLinea(Integer idEstadoLinea) {
        this.idEstadoLinea = idEstadoLinea;
    }
    public String getEstLinNombre() {
        return this.estLinNombre;
    }
    
    public void setEstLinNombre(String estLinNombre) {
        this.estLinNombre = estLinNombre;
    }
    public Set<Linea> getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Set<Linea> lineas) {
        this.lineas = lineas;
    }




}


