package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private Integer idGasto;
     private Cuentas cuentas;
     private TipoGasto tipoGasto;
     private BigDecimal gasValor;
     private Date gasFecha;
     private Date fecha;
     private String gasObservacion;

    public Gasto() {
    }

	
    public Gasto(Cuentas cuentas, TipoGasto tipoGasto, BigDecimal gasValor, Date gasFecha, Date fecha) {
        this.cuentas = cuentas;
        this.tipoGasto = tipoGasto;
        this.gasValor = gasValor;
        this.gasFecha = gasFecha;
        this.fecha = fecha;
    }
    public Gasto(Cuentas cuentas, TipoGasto tipoGasto, BigDecimal gasValor, Date gasFecha, Date fecha, String gasObservacion) {
       this.cuentas = cuentas;
       this.tipoGasto = tipoGasto;
       this.gasValor = gasValor;
       this.gasFecha = gasFecha;
       this.fecha = fecha;
       this.gasObservacion = gasObservacion;
    }
   
    public Integer getIdGasto() {
        return this.idGasto;
    }
    
    public void setIdGasto(Integer idGasto) {
        this.idGasto = idGasto;
    }
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }
    public TipoGasto getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(TipoGasto tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    public BigDecimal getGasValor() {
        return this.gasValor;
    }
    
    public void setGasValor(BigDecimal gasValor) {
        this.gasValor = gasValor;
    }
    public Date getGasFecha() {
        return this.gasFecha;
    }
    
    public void setGasFecha(Date gasFecha) {
        this.gasFecha = gasFecha;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getGasObservacion() {
        return this.gasObservacion;
    }
    
    public void setGasObservacion(String gasObservacion) {
        this.gasObservacion = gasObservacion;
    }




}


