package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Linea generated by hbm2java
 */
public class Linea  implements java.io.Serializable {


     private Integer idLinea;
     private Empresa empresa;
     private EstadoLinea estadoLinea;
     private String linNumero;
     private int linCorte;
     private Date fecha;
     private Set<PlanLinea> planLineas = new HashSet<PlanLinea>(0);
     private Set<VentaLinea> ventaLineas = new HashSet<VentaLinea>(0);
     private Set<SucursalLinea> sucursalLineas = new HashSet<SucursalLinea>(0);
     private Set<Simcard> simcards = new HashSet<Simcard>(0);

    public Linea() {
    }

	
    public Linea(Empresa empresa, EstadoLinea estadoLinea, String linNumero, int linCorte, Date fecha) {
        this.empresa = empresa;
        this.estadoLinea = estadoLinea;
        this.linNumero = linNumero;
        this.linCorte = linCorte;
        this.fecha = fecha;
    }
    public Linea(Empresa empresa, EstadoLinea estadoLinea, String linNumero, int linCorte, Date fecha, Set<PlanLinea> planLineas, Set<VentaLinea> ventaLineas, Set<SucursalLinea> sucursalLineas, Set<Simcard> simcards) {
       this.empresa = empresa;
       this.estadoLinea = estadoLinea;
       this.linNumero = linNumero;
       this.linCorte = linCorte;
       this.fecha = fecha;
       this.planLineas = planLineas;
       this.ventaLineas = ventaLineas;
       this.sucursalLineas = sucursalLineas;
       this.simcards = simcards;
    }
   
    public Integer getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(Integer idLinea) {
        this.idLinea = idLinea;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public EstadoLinea getEstadoLinea() {
        return this.estadoLinea;
    }
    
    public void setEstadoLinea(EstadoLinea estadoLinea) {
        this.estadoLinea = estadoLinea;
    }
    public String getLinNumero() {
        return this.linNumero;
    }
    
    public void setLinNumero(String linNumero) {
        this.linNumero = linNumero;
    }
    public int getLinCorte() {
        return this.linCorte;
    }
    
    public void setLinCorte(int linCorte) {
        this.linCorte = linCorte;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<PlanLinea> getPlanLineas() {
        return this.planLineas;
    }
    
    public void setPlanLineas(Set<PlanLinea> planLineas) {
        this.planLineas = planLineas;
    }
    public Set<VentaLinea> getVentaLineas() {
        return this.ventaLineas;
    }
    
    public void setVentaLineas(Set<VentaLinea> ventaLineas) {
        this.ventaLineas = ventaLineas;
    }
    public Set<SucursalLinea> getSucursalLineas() {
        return this.sucursalLineas;
    }
    
    public void setSucursalLineas(Set<SucursalLinea> sucursalLineas) {
        this.sucursalLineas = sucursalLineas;
    }
    public Set<Simcard> getSimcards() {
        return this.simcards;
    }
    
    public void setSimcards(Set<Simcard> simcards) {
        this.simcards = simcards;
    }




}


