package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer idPago;
     private Cuentas cuentas;
     private Venta venta;
     private TipoPago tipoPago;
     private Date fecha;
     private BigDecimal pagValor;
     private Date pagFechaProx;

    public Pago() {
    }

	
    public Pago(Cuentas cuentas, Venta venta, TipoPago tipoPago, Date fecha, BigDecimal pagValor) {
        this.cuentas = cuentas;
        this.venta = venta;
        this.tipoPago = tipoPago;
        this.fecha = fecha;
        this.pagValor = pagValor;
    }
    public Pago(Cuentas cuentas, Venta venta, TipoPago tipoPago, Date fecha, BigDecimal pagValor, Date pagFechaProx) {
       this.cuentas = cuentas;
       this.venta = venta;
       this.tipoPago = tipoPago;
       this.fecha = fecha;
       this.pagValor = pagValor;
       this.pagFechaProx = pagFechaProx;
    }
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getPagValor() {
        return this.pagValor;
    }
    
    public void setPagValor(BigDecimal pagValor) {
        this.pagValor = pagValor;
    }
    public Date getPagFechaProx() {
        return this.pagFechaProx;
    }
    
    public void setPagFechaProx(Date pagFechaProx) {
        this.pagFechaProx = pagFechaProx;
    }




}


