package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private Integer idPlan;
     private Tercero tercero;
     private Operador operador;
     private String plaNombre;
     private int plaCantidadMinutos;
     private int plaCostoMinuto;
     private int plaCostoMin;
     private int plaCostoMax;
     private Date plaFechaVenc;
     private Date fecha;
     private Set<Convenio> convenios = new HashSet<Convenio>(0);
     private Set<PlanLinea> planLineas = new HashSet<PlanLinea>(0);

    public Plan() {
    }

	
    public Plan(Tercero tercero, Operador operador, String plaNombre, int plaCantidadMinutos, int plaCostoMinuto, int plaCostoMin, int plaCostoMax, Date plaFechaVenc, Date fecha) {
        this.tercero = tercero;
        this.operador = operador;
        this.plaNombre = plaNombre;
        this.plaCantidadMinutos = plaCantidadMinutos;
        this.plaCostoMinuto = plaCostoMinuto;
        this.plaCostoMin = plaCostoMin;
        this.plaCostoMax = plaCostoMax;
        this.plaFechaVenc = plaFechaVenc;
        this.fecha = fecha;
    }
    public Plan(Tercero tercero, Operador operador, String plaNombre, int plaCantidadMinutos, int plaCostoMinuto, int plaCostoMin, int plaCostoMax, Date plaFechaVenc, Date fecha, Set<Convenio> convenios, Set<PlanLinea> planLineas) {
       this.tercero = tercero;
       this.operador = operador;
       this.plaNombre = plaNombre;
       this.plaCantidadMinutos = plaCantidadMinutos;
       this.plaCostoMinuto = plaCostoMinuto;
       this.plaCostoMin = plaCostoMin;
       this.plaCostoMax = plaCostoMax;
       this.plaFechaVenc = plaFechaVenc;
       this.fecha = fecha;
       this.convenios = convenios;
       this.planLineas = planLineas;
    }
   
    public Integer getIdPlan() {
        return this.idPlan;
    }
    
    public void setIdPlan(Integer idPlan) {
        this.idPlan = idPlan;
    }
    public Tercero getTercero() {
        return this.tercero;
    }
    
    public void setTercero(Tercero tercero) {
        this.tercero = tercero;
    }
    public Operador getOperador() {
        return this.operador;
    }
    
    public void setOperador(Operador operador) {
        this.operador = operador;
    }
    public String getPlaNombre() {
        return this.plaNombre;
    }
    
    public void setPlaNombre(String plaNombre) {
        this.plaNombre = plaNombre;
    }
    public int getPlaCantidadMinutos() {
        return this.plaCantidadMinutos;
    }
    
    public void setPlaCantidadMinutos(int plaCantidadMinutos) {
        this.plaCantidadMinutos = plaCantidadMinutos;
    }
    public int getPlaCostoMinuto() {
        return this.plaCostoMinuto;
    }
    
    public void setPlaCostoMinuto(int plaCostoMinuto) {
        this.plaCostoMinuto = plaCostoMinuto;
    }
    public int getPlaCostoMin() {
        return this.plaCostoMin;
    }
    
    public void setPlaCostoMin(int plaCostoMin) {
        this.plaCostoMin = plaCostoMin;
    }
    public int getPlaCostoMax() {
        return this.plaCostoMax;
    }
    
    public void setPlaCostoMax(int plaCostoMax) {
        this.plaCostoMax = plaCostoMax;
    }
    public Date getPlaFechaVenc() {
        return this.plaFechaVenc;
    }
    
    public void setPlaFechaVenc(Date plaFechaVenc) {
        this.plaFechaVenc = plaFechaVenc;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Convenio> getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set<Convenio> convenios) {
        this.convenios = convenios;
    }
    public Set<PlanLinea> getPlanLineas() {
        return this.planLineas;
    }
    
    public void setPlanLineas(Set<PlanLinea> planLineas) {
        this.planLineas = planLineas;
    }




}


