package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer idSucursal;
     private Ciudad ciudad;
     private String sucNombre;
     private String sucDireccion;
     private String sucTelefono;
     private int sucEstado;
     private Set<SucursalTercero> sucursalTerceros = new HashSet<SucursalTercero>(0);
     private Set<SucursalLinea> sucursalLineas = new HashSet<SucursalLinea>(0);
     private Set<SucursalSimcard> sucursalSimcards = new HashSet<SucursalSimcard>(0);

    public Sucursal() {
    }

	
    public Sucursal(Ciudad ciudad, String sucNombre, String sucDireccion, String sucTelefono, int sucEstado) {
        this.ciudad = ciudad;
        this.sucNombre = sucNombre;
        this.sucDireccion = sucDireccion;
        this.sucTelefono = sucTelefono;
        this.sucEstado = sucEstado;
    }
    public Sucursal(Ciudad ciudad, String sucNombre, String sucDireccion, String sucTelefono, int sucEstado, Set<SucursalTercero> sucursalTerceros, Set<SucursalLinea> sucursalLineas, Set<SucursalSimcard> sucursalSimcards) {
       this.ciudad = ciudad;
       this.sucNombre = sucNombre;
       this.sucDireccion = sucDireccion;
       this.sucTelefono = sucTelefono;
       this.sucEstado = sucEstado;
       this.sucursalTerceros = sucursalTerceros;
       this.sucursalLineas = sucursalLineas;
       this.sucursalSimcards = sucursalSimcards;
    }
   
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getSucNombre() {
        return this.sucNombre;
    }
    
    public void setSucNombre(String sucNombre) {
        this.sucNombre = sucNombre;
    }
    public String getSucDireccion() {
        return this.sucDireccion;
    }
    
    public void setSucDireccion(String sucDireccion) {
        this.sucDireccion = sucDireccion;
    }
    public String getSucTelefono() {
        return this.sucTelefono;
    }
    
    public void setSucTelefono(String sucTelefono) {
        this.sucTelefono = sucTelefono;
    }
    public int getSucEstado() {
        return this.sucEstado;
    }
    
    public void setSucEstado(int sucEstado) {
        this.sucEstado = sucEstado;
    }
    public Set<SucursalTercero> getSucursalTerceros() {
        return this.sucursalTerceros;
    }
    
    public void setSucursalTerceros(Set<SucursalTercero> sucursalTerceros) {
        this.sucursalTerceros = sucursalTerceros;
    }
    public Set<SucursalLinea> getSucursalLineas() {
        return this.sucursalLineas;
    }
    
    public void setSucursalLineas(Set<SucursalLinea> sucursalLineas) {
        this.sucursalLineas = sucursalLineas;
    }
    public Set<SucursalSimcard> getSucursalSimcards() {
        return this.sucursalSimcards;
    }
    
    public void setSucursalSimcards(Set<SucursalSimcard> sucursalSimcards) {
        this.sucursalSimcards = sucursalSimcards;
    }




}


