package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SucursalLinea generated by hbm2java
 */
public class SucursalLinea  implements java.io.Serializable {


     private Integer idSucursalLinea;
     private Sucursal sucursal;
     private Linea linea;
     private Date fecha;
     private int sucLinEstado;
     private String sucLinObservacion;

    public SucursalLinea() {
    }

	
    public SucursalLinea(Sucursal sucursal, Linea linea, Date fecha, int sucLinEstado) {
        this.sucursal = sucursal;
        this.linea = linea;
        this.fecha = fecha;
        this.sucLinEstado = sucLinEstado;
    }
    public SucursalLinea(Sucursal sucursal, Linea linea, Date fecha, int sucLinEstado, String sucLinObservacion) {
       this.sucursal = sucursal;
       this.linea = linea;
       this.fecha = fecha;
       this.sucLinEstado = sucLinEstado;
       this.sucLinObservacion = sucLinObservacion;
    }
   
    public Integer getIdSucursalLinea() {
        return this.idSucursalLinea;
    }
    
    public void setIdSucursalLinea(Integer idSucursalLinea) {
        this.idSucursalLinea = idSucursalLinea;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getSucLinEstado() {
        return this.sucLinEstado;
    }
    
    public void setSucLinEstado(int sucLinEstado) {
        this.sucLinEstado = sucLinEstado;
    }
    public String getSucLinObservacion() {
        return this.sucLinObservacion;
    }
    
    public void setSucLinObservacion(String sucLinObservacion) {
        this.sucLinObservacion = sucLinObservacion;
    }




}


