package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SucursalSimcard generated by hbm2java
 */
public class SucursalSimcard  implements java.io.Serializable {


     private Integer idSucSim;
     private Sucursal sucursal;
     private Simcard simcard;
     private Date fecha;
     private String sucSimObservacion;
     private int sucSimEstado;

    public SucursalSimcard() {
    }

	
    public SucursalSimcard(Sucursal sucursal, Simcard simcard, Date fecha, int sucSimEstado) {
        this.sucursal = sucursal;
        this.simcard = simcard;
        this.fecha = fecha;
        this.sucSimEstado = sucSimEstado;
    }
    public SucursalSimcard(Sucursal sucursal, Simcard simcard, Date fecha, String sucSimObservacion, int sucSimEstado) {
       this.sucursal = sucursal;
       this.simcard = simcard;
       this.fecha = fecha;
       this.sucSimObservacion = sucSimObservacion;
       this.sucSimEstado = sucSimEstado;
    }
   
    public Integer getIdSucSim() {
        return this.idSucSim;
    }
    
    public void setIdSucSim(Integer idSucSim) {
        this.idSucSim = idSucSim;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Simcard getSimcard() {
        return this.simcard;
    }
    
    public void setSimcard(Simcard simcard) {
        this.simcard = simcard;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSucSimObservacion() {
        return this.sucSimObservacion;
    }
    
    public void setSucSimObservacion(String sucSimObservacion) {
        this.sucSimObservacion = sucSimObservacion;
    }
    public int getSucSimEstado() {
        return this.sucSimEstado;
    }
    
    public void setSucSimEstado(int sucSimEstado) {
        this.sucSimEstado = sucSimEstado;
    }




}


