package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA



/**
 * TerceroVenta generated by hbm2java
 */
public class TerceroVenta  implements java.io.Serializable {


     private Integer idTerVen;
     private Tercero tercero;
     private Venta venta;
     private int terVenTipo;

    public TerceroVenta() {
    }

    public TerceroVenta(Tercero tercero, Venta venta, int terVenTipo) {
       this.tercero = tercero;
       this.venta = venta;
       this.terVenTipo = terVenTipo;
    }
   
    public Integer getIdTerVen() {
        return this.idTerVen;
    }
    
    public void setIdTerVen(Integer idTerVen) {
        this.idTerVen = idTerVen;
    }
    public Tercero getTercero() {
        return this.tercero;
    }
    
    public void setTercero(Tercero tercero) {
        this.tercero = tercero;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getTerVenTipo() {
        return this.terVenTipo;
    }
    
    public void setTerVenTipo(int terVenTipo) {
        this.terVenTipo = terVenTipo;
    }




}


