package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private Integer idTipoPago;
     private String tpagoNombre;
     private String tpagoDescripcion;
     private Set<Pago> pagos = new HashSet<Pago>(0);

    public TipoPago() {
    }

	
    public TipoPago(String tpagoNombre) {
        this.tpagoNombre = tpagoNombre;
    }
    public TipoPago(String tpagoNombre, String tpagoDescripcion, Set<Pago> pagos) {
       this.tpagoNombre = tpagoNombre;
       this.tpagoDescripcion = tpagoDescripcion;
       this.pagos = pagos;
    }
   
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public String getTpagoNombre() {
        return this.tpagoNombre;
    }
    
    public void setTpagoNombre(String tpagoNombre) {
        this.tpagoNombre = tpagoNombre;
    }
    public String getTpagoDescripcion() {
        return this.tpagoDescripcion;
    }
    
    public void setTpagoDescripcion(String tpagoDescripcion) {
        this.tpagoDescripcion = tpagoDescripcion;
    }
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


