package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoGasto generated by hbm2java
 */
public class TipoGasto  implements java.io.Serializable {


     private Integer idTipoGasto;
     private String tgastoNombre;
     private String tgastoDescripcion;
     private Set<Gasto> gastos = new HashSet<Gasto>(0);

    public TipoGasto() {
    }

	
    public TipoGasto(String tgastoNombre) {
        this.tgastoNombre = tgastoNombre;
    }
    public TipoGasto(String tgastoNombre, String tgastoDescripcion, Set<Gasto> gastos) {
       this.tgastoNombre = tgastoNombre;
       this.tgastoDescripcion = tgastoDescripcion;
       this.gastos = gastos;
    }
   
    public Integer getIdTipoGasto() {
        return this.idTipoGasto;
    }
    
    public void setIdTipoGasto(Integer idTipoGasto) {
        this.idTipoGasto = idTipoGasto;
    }
    public String getTgastoNombre() {
        return this.tgastoNombre;
    }
    
    public void setTgastoNombre(String tgastoNombre) {
        this.tgastoNombre = tgastoNombre;
    }
    public String getTgastoDescripcion() {
        return this.tgastoDescripcion;
    }
    
    public void setTgastoDescripcion(String tgastoDescripcion) {
        this.tgastoDescripcion = tgastoDescripcion;
    }
    public Set<Gasto> getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set<Gasto> gastos) {
        this.gastos = gastos;
    }




}


