package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Date venFecha;
     private Date fecha;
     private BigDecimal venDomicilio;
     private BigDecimal venSaldo;
     private Set<VentaLinea> ventaLineas = new HashSet<VentaLinea>(0);
     private Set<TerceroVenta> terceroVentas = new HashSet<TerceroVenta>(0);
     private Set<Pago> pagos = new HashSet<Pago>(0);

    public Venta() {
    }

	
    public Venta(Date venFecha, Date fecha, BigDecimal venDomicilio, BigDecimal venSaldo) {
        this.venFecha = venFecha;
        this.fecha = fecha;
        this.venDomicilio = venDomicilio;
        this.venSaldo = venSaldo;
    }
    public Venta(Date venFecha, Date fecha, BigDecimal venDomicilio, BigDecimal venSaldo, Set<VentaLinea> ventaLineas, Set<TerceroVenta> terceroVentas, Set<Pago> pagos) {
       this.venFecha = venFecha;
       this.fecha = fecha;
       this.venDomicilio = venDomicilio;
       this.venSaldo = venSaldo;
       this.ventaLineas = ventaLineas;
       this.terceroVentas = terceroVentas;
       this.pagos = pagos;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Date getVenFecha() {
        return this.venFecha;
    }
    
    public void setVenFecha(Date venFecha) {
        this.venFecha = venFecha;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getVenDomicilio() {
        return this.venDomicilio;
    }
    
    public void setVenDomicilio(BigDecimal venDomicilio) {
        this.venDomicilio = venDomicilio;
    }
    public BigDecimal getVenSaldo() {
        return this.venSaldo;
    }
    
    public void setVenSaldo(BigDecimal venSaldo) {
        this.venSaldo = venSaldo;
    }
    public Set<VentaLinea> getVentaLineas() {
        return this.ventaLineas;
    }
    
    public void setVentaLineas(Set<VentaLinea> ventaLineas) {
        this.ventaLineas = ventaLineas;
    }
    public Set<TerceroVenta> getTerceroVentas() {
        return this.terceroVentas;
    }
    
    public void setTerceroVentas(Set<TerceroVenta> terceroVentas) {
        this.terceroVentas = terceroVentas;
    }
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


