package model;
// Generated 23/04/2013 02:19:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * VentaLinea generated by hbm2java
 */
public class VentaLinea  implements java.io.Serializable {


     private Integer idVentaLinea;
     private Venta venta;
     private Linea linea;
     private BigDecimal ventLinPrecio;
     private int ventLinTipo;
     private BigDecimal ventLinDeposito;

    public VentaLinea() {
    }

    public VentaLinea(Venta venta, Linea linea, BigDecimal ventLinPrecio, int ventLinTipo, BigDecimal ventLinDeposito) {
       this.venta = venta;
       this.linea = linea;
       this.ventLinPrecio = ventLinPrecio;
       this.ventLinTipo = ventLinTipo;
       this.ventLinDeposito = ventLinDeposito;
    }
   
    public Integer getIdVentaLinea() {
        return this.idVentaLinea;
    }
    
    public void setIdVentaLinea(Integer idVentaLinea) {
        this.idVentaLinea = idVentaLinea;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public BigDecimal getVentLinPrecio() {
        return this.ventLinPrecio;
    }
    
    public void setVentLinPrecio(BigDecimal ventLinPrecio) {
        this.ventLinPrecio = ventLinPrecio;
    }
    public int getVentLinTipo() {
        return this.ventLinTipo;
    }
    
    public void setVentLinTipo(int ventLinTipo) {
        this.ventLinTipo = ventLinTipo;
    }
    public BigDecimal getVentLinDeposito() {
        return this.ventLinDeposito;
    }
    
    public void setVentLinDeposito(BigDecimal ventLinDeposito) {
        this.ventLinDeposito = ventLinDeposito;
    }




}


